name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Lancer les tests
      - name: Run tests
        run: |
          python -m unittest discover

      # Étape 5 : Déplacer index.html vers la racine (si nécessaire)
      - name: Move index.html to root
        run: cp templates/index.html .

      # Étape 6 : Préparer les fichiers pour le déploiement
      - name: Zip artifact for deployment
        run: zip -r release.zip home.html app.py requirements.txt

      # Étape 7 : Télécharger l’artefact pour le déploiement
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: your-app
          path: |
            release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      # Étape 1 : Télécharger l’artefact depuis le job build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: your-app

      # Étape 2 : Dézipper les fichiers pour le déploiement
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Étape 3 : Connexion à Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Étape 4 : Déployer sur Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bmr-bmiwebapp'
          slot-name: 'Production'
          package: './release.zip'
